###db
#DB_USER: carrot123
#DB_PASSWORD: carrot123!@
#DBL_URL: jdbc:mysql://localhost:3306/carrottruck?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#
###jwt
#JWT_SECRET: temp_password
#
###email
#EMAIL_ID: carrot.truck.noreply@gmail.com
#EMAIL_PASSWORD: qoaktkwfolwfjkdt
#
###social-google
##OAUTH2_GOOGLE_ID: 959258029329-0u075vev112cmjl4ochnt3ln27j8r7hu.apps.googleusercontent.com
##OAUTH2_GOOGLE_PASSWORD: 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
#
###social-kakao
##OAUTH2_KAKAO_REDIRECT_URL: http://localhost:3000/oauth/kakao/callback
##OAUTH2_KAKAO_REST_API: 0995822231823eb8a5fc4ec57bd81ffc
#
###naver-maps
#NAVER_CLIENT_ID: z4ar4pfdyx
#NAVER_CLIENT_SECRET: bL3wthmh5dwQJdpX6BCdyvfKlnZzaqh6IslL2R1e
#NAVER_GEOCODE_URL: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
#NAVER_REVERSE_GEOCODE_URL: https://naveropenapi.apigw.ntruss.com/map-reversegeocode/v2/gc
#
###store-info
#DATA_GO_SERVICE_KEY: gIZjCIoN%2F3%2Bg6yNigkQhmUXwwUIYoIy%2Be5EgYLXQNEejueCScUiEmgkXclnBUBm55x1aVsQYPwSawoQlOUWwQA%3D%3D
#STORE_DONG_URL: http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong
#STORE_RADIUS_URL: http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInRadius
#DONG_CODE_URL: http://apis.data.go.kr/1741000/StanReginCd/getStanReginCdList
#
### redis
#REDIS_HOST: k9c211.p.ssafy.io
#REDIS_PORT: 6379
#REDIS_PASSWORD: carrot123!@
#
### Amazon S3
#ACCESS_KEY: AKIAYCYO66WIZYCRYK5I
#SECRET_KEY: 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
#
### Port One API
#PORT_ONE_KEY: 3763638803177338
#PORT_ONE_SECRET: Of4RZGOh4TYtb2khpflQbwMfVITDeeLY4Z8yQdUcBaZ4nWcUi0DuzmUK41U9EKxbhZZSjIqfO7bxh561
#
#---
#
###dev
#spring:
#  config:
#    activate:
#      on-profile: dev
#
###db
#MYSQL_USER: carrot123
#MYSQL_PASSWORD: carrot123!@
#MYSQL_URL: jdbc:mysql://localhost:3306/carrottruck?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#
#---
#
###server
#spring:
#  config:
#    activate:
#      on-profile: server
#
###db
#MYSQL_USER: carrot123
#MYSQL_PASSWORD: carrot123!@
#MYSQL_URL: jdbc:mysql://k9c211.p.ssafy.io:3306/carrottruck?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8