spring:

  # database setting
  datasource:
    url: jdbc:h2:mem:~/ireonTest
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # reserved words error config (add backticks)
        auto_quote_keyword: false
        globally_quoted_identifiers: false
    open-in-view: true
    defer-datasource-initialization: true

  # redis
  data:
    redis:
      host: localhost
      port: 6379

  # SMTP
  mail:
  host: smtp.gmail.com
  port: 587
  username: ireon.mail@gmail.com
  password: vcaqyweytwimwqno
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

# log setting
logging:
  level:
    org.hibernate.sql: debug
    com.boyworld.carrot: debug

server:
  port: 8080

# file path
file:
  dir: /var/images

cloud:
  aws:
    s3:
      bucket: uhpoo
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false