spring:
  profiles:
    include: dev, env  #dev
  #    include: server, env  #server

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    path: logs
jwt:
  secret: ${JWT_SECRET}
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api